"""
pdf_exporter.py - PDF generation for puzzle pieces and reference sheet.
Uses fpdf2.
"""

import os
from PIL import Image
from fpdf import FPDF


class PuzzlePDF(FPDF):
    """Custom PDF class for puzzle output."""

    def __init__(self, orientation="P", unit="mm", format="A4"):
        super().__init__(orientation=orientation, unit=unit, format=format)
        self.set_auto_page_break(False)

    def _mm_to_pt(self, mm):
        return mm * 72 / 25.4

    def add_piece(self, piece_img, x, y, max_w, max_h):
        """Add a single piece image to the PDF at (x,y)."""
        pw, ph = piece_img.size
        aspect = pw / ph
        if max_w / max_h > aspect:
            draw_h = max_h
            draw_w = draw_h * aspect
        else:
            draw_w = max_w
            draw_h = draw_w / aspect

        self.image(piece_img, x=x, y=y, w=draw_w, h=draw_h)

    def header(self):
        pass

    def footer(self):
        if getattr(self, "_watermark", False):
            self.set_y(-14)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, "Made with Puzzly - puzzly.pythonanywhere.com", align="C")
        else:
            self.set_y(-14)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(70, 70, 70)
            self.cell(0, 10, "Generated by Puzzly", align="C")

    def add_titled_image(self, img, title, margin=15, top=20, bottom=18):
        """Add an image centred on a page with a visible dark title up top.

        The title reserves the top band so it never sits on a white area
        with white text, and the footer reserves the bottom band so the
        image never covers it."""
        page_w, page_h = self.w, self.h
        avail_w = page_w - 2 * margin
        avail_h = page_h - top - bottom
        iw, ih = img.size
        aspect = iw / ih if ih else 1
        if avail_w / avail_h > aspect:
            draw_h = avail_h
            draw_w = draw_h * aspect
        else:
            draw_w = avail_w
            draw_h = draw_w / aspect
        x = margin + (avail_w - draw_w) / 2
        y = top + (avail_h - draw_h) / 2

        self.set_xy(margin, 7)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(35, 35, 35)
        self.cell(avail_w, 9, title, align="C")

        self.image(img, x=x, y=y, w=draw_w, h=draw_h)


def _rgba_to_rgb(img, bg_color=(255, 255, 255)):
    """Convert RGBA image to RGB by compositing onto a background color."""
    if img.mode != "RGBA":
        return img.convert("RGB")
    bg = Image.new("RGB", img.size, bg_color)
    bg.paste(img, mask=img.split()[3])
    return bg


# Paper sizes in mm
PAPER_SIZES = {
    "A4": (210, 297),
    "Letter": (216, 279),
    "A3": (297, 420),
}


def calculate_piece_page_layout(
    pieces, paper_size="A4", margin_mm=15, pieces_per_row=None
):
    """Calculate how to lay out pieces on a page.
    Returns list of pages, each page is list of (piece, x, y, draw_w, draw_h)."""
    page_w, page_h = PAPER_SIZES.get(paper_size, (210, 297))
    margin = margin_mm
    avail_w = page_w - 2 * margin
    avail_h = page_h - 2 * margin

    # Determine max piece size / aspect so all pieces fit their cells
    max_pw = max(p.size[0] for p in pieces)
    max_ph = max(p.size[1] for p in pieces)
    max_aspect = max_pw / max_ph if max_ph > 0 else 1

    n = len(pieces)

    def fit_for(per_row):
        """Return (pieces_per_page, cell_w, cell_h) for a given columns count."""
        if per_row < 1:
            per_row = 1
        cell_w = avail_w / per_row
        cell_h = cell_w / max_aspect
        per_col = max(1, int(avail_h // cell_h))
        return per_row * per_col, cell_w, cell_h

    if pieces_per_row is None:
        # Pick the column count that packs the most pieces per page.
        best_per_row = 1
        best_ppp = 0
        for per_row in range(1, n + 1):
            ppp, _, _ = fit_for(per_row)
            if ppp > best_ppp:
                best_ppp = ppp
                best_per_row = per_row
        pieces_per_row = best_per_row

    _, max_cell_w, max_cell_h = fit_for(pieces_per_row)
    per_col = max(1, int(avail_h // max_cell_h))

    pages = []
    current_page = []
    row, col = 0, 0
    start_y = margin

    for piece in pieces:
        pw, ph = piece.size
        aspect = pw / ph
        if max_cell_w / max_cell_h > aspect:
            draw_h = max_cell_h * 0.90
            draw_w = draw_h * aspect
        else:
            draw_w = max_cell_w * 0.90
            draw_h = draw_w / aspect

        x = margin + col * max_cell_w + (max_cell_w - draw_w) / 2
        y = start_y + row * max_cell_h

        current_page.append((piece, x, y, draw_w, draw_h))

        col += 1
        if col >= pieces_per_row:
            col = 0
            row += 1
            if row >= per_col:
                pages.append(current_page)
                current_page = []
                row = 0

    if current_page:
        pages.append(current_page)
    return pages


def generate_pdf(
    image_path,
    output_path,
    rows,
    cols,
    puzzle_type="grid",
    border_width=3,
    paper_size="A4",
    layout="scattered",
    pages=None,
    tab_style="classic",
    watermark=False,
):
    """Generate a printable PDF. `pages` is a list selecting which pages to
    include, in this fixed order:
        'framed'    - framed puzzle board (picture + frame + cut lines)
        'pieces'    - cut-out pieces (scattered) OR one-page picture
        'reference' - reference / answer sheet
        'template'  - blank placement template board
    Pass e.g. ['framed'] to export a single page."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    from puzzle_maker import (
        generate_grid_pieces,
        generate_jigsaw_pieces,
        create_reference_image,
        create_single_page_image,
        create_template_image,
        create_framed_puzzle_image,
    )
    from PIL import Image as PILImage

    if not pages:
        pages = ["framed", "pieces", "reference", "template"]

    pdf = PuzzlePDF(format=paper_size)
    pdf._watermark = watermark
    page_w, page_h = PAPER_SIZES.get(paper_size, (210, 297))
    margin = 15

    if "framed" in pages:
        pdf.add_page()
        framed = create_framed_puzzle_image(
            image_path, rows, cols, puzzle_type, border_width, tab_style=tab_style
        )
        pdf.add_titled_image(_rgba_to_rgb(framed), "Puzzly - Framed puzzle board")

    if "pieces" in pages:
        if layout == "single":
            pdf.add_page()
            single_img = create_single_page_image(
                image_path, rows, cols, puzzle_type, border_width, tab_style=tab_style
            )
            pdf.add_titled_image(
                _rgba_to_rgb(single_img), "Puzzly - Cut & assemble in place"
            )
        else:
            if puzzle_type == "grid":
                pieces = generate_grid_pieces(image_path, rows, cols, border_width)
            else:
                pieces = generate_jigsaw_pieces(image_path, rows, cols, border_width, tab_style=tab_style)
            pieces_rgb = [_rgba_to_rgb(p) for p in pieces]
            laid_pages = calculate_piece_page_layout(pieces_rgb, paper_size)
            for i, page in enumerate(laid_pages):
                pdf.add_page()
                if i == 0:
                    pdf.set_xy(margin, 7)
                    pdf.set_font("Helvetica", "B", 11)
                    pdf.set_text_color(35, 35, 35)
                    pdf.cell(
                        page_w - 2 * margin, 9, "Puzzly - Cut-out pieces", align="C"
                    )
                for piece, x, y, dw, dh in page:
                    pdf.image(piece, x=x, y=y, w=dw, h=dh)

    if "reference" in pages:
        pdf.add_page()
        ref_img = create_reference_image(image_path, rows, cols, puzzle_type, tab_style=tab_style)
        pdf.add_titled_image(_rgba_to_rgb(ref_img), "Puzzly - Reference sheet")

    if "template" in pages:
        pdf.add_page()
        with PILImage.open(image_path) as tmp_img:
            ow, oh = tmp_img.size
        temp_img = create_template_image(
            rows, cols, puzzle_type, ow, oh, border_width, image_path, tab_style=tab_style
        )
        pdf.add_titled_image(_rgba_to_rgb(temp_img), "Puzzly - Placement template")

    pdf.output(output_path)
    return output_path
